server:
  port: 8080
# mybatis 配置
mybatis:
  typeAliasesPackage: com.tingda.demo.entity
  mapperLocations: classpath:mapper/*.xml

spring:
  #数据连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
# 自动部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

logging:
  config: classpath:logback-spring.xml
  path: D:/nmyslog/nmys


